/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TemperatureConverter;

/**
 *
 * @author Arthas
 */
public class TemperatureConverterGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form TemperatureConverterGUI
     */
    public TemperatureConverterGUI() {
        initComponents();
        txtConvertedTemperature.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        rBtnCelsius = new javax.swing.JRadioButton();
        rBtnFah = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtConvertedTemperature = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter Temperature");

        rBtnCelsius.setText("Convert to Celsius");

        rBtnFah.setText("Convert to Fahrenheit");

        btnSubmit.setText("Calculate");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Converted Temperature");

        txtConvertedTemperature.setText("Temp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit)
                    .addComponent(rBtnFah)
                    .addComponent(rBtnCelsius)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConvertedTemperature))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rBtnCelsius)
                .addGap(18, 18, 18)
                .addComponent(rBtnFah)
                .addGap(27, 27, 27)
                .addComponent(btnSubmit)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConvertedTemperature))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
       String temperature = txtTemperature.getText();
       Double temp = Double.parseDouble(temperature);
       
       if (rBtnCelsius.isSelected()) {
           Double newTemp = (temp - 32) * 9/5;
           String newTempString = Double.toString(newTemp);
           txtConvertedTemperature.setText(newTempString);
           txtConvertedTemperature.setVisible(true);
       }else if (rBtnFah.isSelected()) {
           Double newTemp = (temp * 9/5) + 32;
           String newTempString = Double.toString(newTemp);
           txtConvertedTemperature.setText(newTempString);
           txtConvertedTemperature.setVisible(true);
       }
       
       
    }//GEN-LAST:event_btnSubmitActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rBtnCelsius;
    private javax.swing.JRadioButton rBtnFah;
    private javax.swing.JLabel txtConvertedTemperature;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
}
